//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SCICompanionLib.rc
//
#define ID_GENERATELIPSYNC              4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_SCIPicEditorTYPE            129
#define IDS_CHOOSEAPRIORITY             129
#define IDC_CURSORPEN                   130
#define IDS_CHOOSEACONTROL              130
#define IDC_CURSORHISTORY               131
#define ID_INDICATOR_WORD               131
#define IDC_CURSORLINE                  132
#define IDS_CHOOSEATRANSPARENCY         132
#define IDC_CURSORZOOM                  133
#define ID_INDICATOR_RESSIZE            133
#define IDC_CURSORFILL                  134
#define ID_INDICATOR_BROWSEERROR        134
#define IDR_TOOLBARTOOLS                137
#define IDR_TOOLBARPIC                  137
#define IDD_DIALOGCOLOR                 141
#define IDD_DIALOG1                     144
#define IDD_DIALOG2                     145
#define IDD_DEFINEPALETTE               145
#define IDD_MAINSLIDER                  146
#define IDD_DIALOGPATTERN               147
#define IDD_RESOURCENUM                 148
#define IDR_TOOLBARVIEWS                149
#define IDR_TOOLBARCOMMANDVIEW          151
#define IDD_PREFERENCES                 153
#define IDD_DIALOG3                     154
#define IDD_VPC                         154
#define IDD_DIALOGPRICON                155
#define IDD_DEFINEPALETTE2              156
#define IDD_DONTSHOWAGAIN               158
#define IDD_ALPHASLIDER                 159
#define IDC_CURSORPASTE                 160
#define IDC_CURSORLINE1                 161
#define IDC_CURSORPLACEMENT             161
#define IDR_TOOLBARSCRIPT               162
#define IDR_TOOLBARDRAWVIEW             163
#define IDD_NEWROOM                     164
#define IDD_INSERTSCIOBJECT             165
#define IDD_VOCABAUTOCOMPLETE           166
#define IDD_NEWSCRIPT                   167
#define IDR_MENUSCRIPT                  168
#define IDR_MENUVOCAB                   169
#define IDD_DIALOGCEL                   170
#define IDD_DIALOGANIMATE               173
#define IDC_CURSORSHAPE                 174
#define IDC_CURSORSHAPETEMP             174
#define IDD_DIALOGFINDALL               175
#define IDD_COMPILEDIALOG               176
#define IDR_TOOLBARVOCAB                177
#define IDD_DIALOGFINDWORD              179
#define IDB_BITMAPUP                    180
#define IDD_COLORADVANCED               180
#define IDB_BITMAPDOWN                  181
#define IDB_BITMAPLEFT                  182
#define IDB_BITMAPRIGHT                 183
#define IDB_BITMAPTEST                  189
#define IDD_DIALOG4                     191
#define IDD_BITMAPTOPIC                 191
#define IDD_DIALOG5                     192
#define IDB_OVERLAYOLD                  193
#define IDB_OVERLAYOLD40                195
#define IDB_CORRUPTRESOURCE             196
#define IDR_TOOLBARFONT                 197
#define IDR_TOOLBARTEXT                 199
#define IDC_CURSORRESIZENS_BR           201
#define IDD_GAMEPROPERTIESDIALOG        202
#define IDC_CURSORRESIZENS_TL           202
#define IDR_MENUVIEWITEM                203
#define IDC_CURSORRESIZENS_STRETCH      203
#define IDR_MENUVIEWBG                  204
#define IDC_CURSORRESIZEWE_BR           205
#define IDC_CURSORRESIZEWE_TL           206
#define IDC_CURSORRESIZEWE_STRETCH      207
#define IDC_CURSORRESIZENSWE_BR         208
#define IDC_CURSORRESIZENSWE_STRETCH    209
#define IDB_BITMAPCONVERT               209
#define IDC_CURSORRESIZENSWE_TL         210
#define IDI_ICONCONVERT                 210
#define IDD_CLASSBROWSERDIALOG          211
#define IDC_CURSORROTATE                211
#define IDB_CLASSBROWSER                212
#define IDD_DIALOG_GOTO                 213
#define IDC_CURSORUP                    214
#define IDC_CURSORDOWN                  215
#define IDR_MENUFAKEEGO                 215
#define IDC_CURSORRIGHT                 216
#define IDB_ALPHABLEND                  216
#define IDC_CURSORLEFT                  217
#define IDD_VISUALSCRIPTDIALOG          217
#define IDB_ALPHABLENDWHITE             217
#define IDB_BITMAPOBJECTTREE            218
#define IDR_VOCABFRAME                  220
#define IDR_TEXTFRAME                   221
#define IDR_SCRIPTFRAME                 222
#define IDI_ICON1                       227
#define IDI_APPICON                     228
#define IDI_ICON2                       231
#define IDI_BANG                        231
#define IDD_NEWGAMEDIALOG               232
#define IDC_CURSOR1                     233
#define IDC_CURSORCIRCLE                233
#define IDD_DIALOGCELFONT2              235
#define IDD_DIALOGCELCURSOR2            236
#define IDD_DIALOGCELVIEW2              237
#define IDD_PICCOMMANDS                 238
#define IDR_TOOLBAR1                    239
#define IDR_TOOLBAR_PICSLIDER           239
#define IDR_TOOLBARPALETTES             243
#define IDR_TOOLBARSOUND                244
#define IDD_DIALOG6                     245
#define IDD_DIALOGEMPTY                 245
#define IDD_QUICKSCRIPTS                246
#define IDI_ICONTEST                    247
#define IDB_RESOURCETYPES               248
#define IDD_PREVIEWPIC                  249
#define IDD_PREVIEWVIEW                 250
#define IDD_PREVIEWSCRIPT               251
#define IDR_ACCELERATORPICCOMMANDS      251
#define IDD_PREVIEWTEXT                 252
#define IDB_BITMAPNOPIC                 252
#define IDD_PREVIEWFONT                 253
#define IDR_ACCELERATORRASTERBAR        253
#define IDR_MENUVIEWS                   254
#define IDD_QUICKSCRIPTS1               254
#define IDD_SAMPLES                     254
#define IDR_ACCELERATORMESSAGEEDIT      254
#define IDB_BITMAPNULL                  255
#define IDD_PREVIEWBLANK                255
#define ID_BROWSEINFOPANE               256
#define IDD_PREVIEWSOUND                256
#define IDB_BITMAPLOOP                  256
#define ID_SCRIPT_CLASSCOMBO            257
#define IDD_SOUNDTOOLBOX                257
#define IDB_BITMAPCUE                   257
#define ID_SCRIPT_FUNCTIONCOMBO         258
#define IDB_BITMAP1                     260
#define IDB_BITMAPAFFECTALL             260
#define IDB_BITMAPCUEACTIVE             261
#define IDI_ICONMAINTEXT                261
#define IDB_TABSCRIPT                   262
#define IDB_BITMAP3                     263
#define IDB_TABVIEW                     265
#define IDB_BITMAP6                     266
#define IDB_TABPIC                      266
#define IDB_BITMAP7                     267
#define IDB_TABPICNS                    267
#define IDI_ICON4                       268
#define IDI_COMPILEALL                  268
#define IDI_BRUSH                       269
#define IDI_REPLACECOLOUR               270
#define IDI_ZOOM                        271
#define IDI_EDIT_COPY                   272
#define IDI_EDIT_CUT                    274
#define IDI_EDIT_PASTE                  275
#define IDI_FILE_OPEN                   276
#define IDI_FILE_SAVE                   277
#define IDI_REBUILDRESOURCES            278
#define IDI_RUNGAME                     279
#define IDI_HISTORY                     280
#define IDI_COMPILE                     281
#define IDI_SOUND                       282
#define IDI_BACK                        283
#define IDI_FORWARD                     284
#define IDI_GAMEPROPERTIES              285
#define IDI_NEWSOUND                    286
#define IDI_PATCH                       287
#define IDI_FONT                        288
#define IDI_NEWFONT                     289
#define IDI_NEWPIC                      290
#define IDI_NEWSCRIPT                   291
#define IDI_NEWVIEW                     292
#define IDI_SCRIPT                      294
#define IDI_VIEW                        295
#define IDI_VOCAB                       296
#define IDI_NEWTEXT                     297
#define IDI_TEXT                        298
#define IDI_PREFERENCES                 299
#define IDI_NEWCURSOR                   300
#define IDI_CURSOR                      301
#define IDB_BITMAP4                     303
#define IDB_VPCHIGHLIGHT                303
#define IDB_BITMAP8                     304
#define IDB_VPCHIGHLIGHTX               304
#define IDI_PIC                         305
#define IDI_SHOWTRACEIMAGE              306
#define IDI_LOADTRACEIMAGE              307
#define IDI_DELETE                      308
#define IDI_EDIT_FIND                   309
#define IDI_ANIMATE                     310
#define IDI_PALETTE                     311
#define IDI_IMAGESEQUENCE               312
#define IDI_VIEWDETAILS                 313
#define IDI_VIEWICONS                   314
#define IDI_SCRIPT_CONVERT              315
#define IDI_SCRIPT_INSERT_OBJECT        316
#define IDI_NEWROOM                     317
#define IDI_NEWWORD                     318
#define IDI_MOVEUP                      319
#define IDI_MOVEDOWN                    320
#define IDI_STOP                        321
#define IDI_PLAY                        322
#define IDI_PAUSE                       323
#define IDI_RECT                        324
#define IDI_ROUNDEDRECT_SOLID           325
#define IDI_ROUNDEDRECT                 326
#define IDI_ELLIPSE_SOLID               327
#define IDI_ELLIPSE                     328
#define IDI_RECT_SOLID                  329
#define IDI_LINE                        330
#define IDI_FLIPHORZ                    331
#define IDI_FLIPVERT                    332
#define IDI_INVERT                      333
#define IDI_GREYSCALE                   334
#define IDI_LIGHTUP                     335
#define IDI_PLACEMENT                   336
#define IDI_DITHER                      337
#define IDI_FAKEEGO                     338
#define IDI_PRIORITYLINES               339
#define IDI_PALETTE0                    340
#define IDI_PALETTE3                    341
#define IDI_PALETTE1                    342
#define IDI_PALETTE2                    343
#define IDR_TOOLBARSCREENS              344
#define IDR_TOOLBARMESSAGE              345
#define IDI_SCREENCONTROL               346
#define IDI_SCREENVISUAL                347
#define IDI_SCREENPRIORITY              348
#define IDI_FLOODFILL                   349
#define IDB_BITMAP9                     350
#define IDB_PICTHUMB_HIGHLIGHT          350
#define IDD_REMOVESCRIPT                351
#define IDB_CLOSE_ACTIVE                352
#define IDD_DIALOGVERSION               352
#define IDB_CLOSE_INACTIVE              353
#define IDI_PALETTEVGA                  354
#define IDB_MESSAGEAUDIOICONS           354
#define IDD_PICCOMMANDS_VGA             355
#define IDD_DIALOGCHOOSECOLORVGA        356
#define IDI_ICON3                       357
#define IDD_DIALOGCOLOR1                357
#define IDD_DIALOGCOLORVGA              357
#define IDI_ICON5                       358
#define IDD_BITMAPTOVGA                 358
#define IDI_EYEDROPPER                  359
#define IDD_SAMPLES1                    359
#define IDD_PICHELPER                   359
#define IDC_CURSOREYEDROPPER            360
#define IDD_EXTRACTALL                  360
#define IDI_TRANSPARENCY                361
#define IDC_CURSORPOLYGON               361
#define IDR_MENUPICBG                   362
#define IDD_PALETTE_EDITOR              363
#define IDD_PALETTE_EDITOR1             364
#define IDD_PALETTE_EDITOR_EMBEDDED     364
#define IDR_MENUDELETEPOINT             364
#define IDD_DECOMPILER                  365
#define IDR_MENUSPLITEDGE               365
#define IDD_MESSAGETOOLBOX              366
#define IDD_MESSAGEHELPER               367
#define IDD_MESSAGEEDIT                 368
#define IDI_MESSAGE                     369
#define IDI_NEWMESSAGE                  370
#define IDI_NEWPALETTE                  371
#define IDI_AUDIO                       372
#define IDI_EDITPALETTE                 373
#define IDD_DIALOGGRADIENTS             374
#define IDI_NEWMESSAGEENTRY             375
#define IDI_NEWMESSAGESEQ               376
#define IDI_CLONEMESSAGEENTRY           377
#define IDI_POLYPATH                    378
#define IDD_PICCOMMANDS_VGA1            379
#define IDI_OPENGAMEFOLDER              380
#define IDI_DEBUG                       381
#define IDI_DEBUGROOM                   382
#define IDD_OUTPUTPANE                  383
#define IDI_STOPDEBUG                   384
#define IDD_PREVIEWAUDIO                384
#define IDD_CONVERTTOPALETTE            385
#define IDD_PALETTEADJUST               386
#define IDD_PICSIZE                     387
#define IDI_REFRESH                     388
#define IDD_COLOR_SHIFTER               388
#define IDI_RIGHT_ARROW                 389
#define IDD_LIPSYNCDIALOG               389
#define IDD_VIEWLOOP                    390
#define IDR_MENUEGOS                    391
#define IDD_PREFERENCES1                391
#define IDD_AUDIOPREFERENCES            391
#define IDI_RECORD                      392
#define IDD_AUDIOEDIT                   392
#define IDI_MONITOR                     393
#define ID_INDICATOR_AUDIOSIZE          394
#define IDI_CD                          395
#define IDD_PHONEMEEDITOR               397
#define IDI_WAVEFORM                    398
#define IDC_CHOOSECOLORSTATIC           1001
#define IDC_BUTTON1                     1003
#define IDC_BUTTONDOWN                  1003
#define IDC_BUTTONADVANCED              1003
#define IDC_BUTTONCONVERT               1003
#define IDC_BUTTONPLAY                  1003
#define IDC_BUTTONPRINT                 1003
#define IDC_BUTTONANIMATE               1003
#define IDC_BUTTON2                     1004
#define IDC_SETVISUAL                   1004
#define IDC_BUTTON_TRANSPARENCY         1004
#define IDC_BUTTONBROWSE                1004
#define IDC_BUTTONMOVE                  1004
#define IDC_BUTTONBG                    1004
#define IDC_BUTTON3                     1005
#define IDC_SETPENSTYLE                 1005
#define IDC_BUTTON_ADDCELAFTER          1005
#define IDC_BUTTONCLIPBOARD             1005
#define IDC_BUTTON_EXPORT               1005
#define IDC_BUTTON4                     1006
#define IDC_SETCONTROL                  1006
#define IDC_BUTTON_ADDLOOPAFTER         1006
#define IDC_PALETTECOLORS               1007
#define IDC_SETPRIORITY                 1007
#define IDC_BUTTONUP                    1007
#define IDC_SLIDER1                     1008
#define IDC_BUTTONRIGHT                 1008
#define IDC_CHOOSEBRUSHSTATIC           1009
#define IDC_BUTTONLEFT                  1009
#define IDC_PALETTEPREVIEW              1010
#define IDC_TAB1                        1011
#define IDC_PALETTETAB                  1011
#define IDC_TABS                        1011
#define IDC_EDITPACKAGE                 1012
#define IDC_EDITRESOURCE                1013
#define IDC_FAKEEGOX                    1014
#define IDC_FAKEEGOY                    1015
#define IDC_GLOBALPALETTES              1016
#define IDC_DRAWGRIDLINES               1017
#define IDC_TOGGLEVISUAL                1018
#define IDC_TOGGLEPRIORITY              1019
#define IDC_TOGGLECONTROL               1020
#define IDC_DIALOGDESCRIPTION           1022
#define IDC_USERANDOMPATTERNS           1023
#define IDC_CUSTOM1                     1025
#define IDC_BROWSER                     1025
#define IDC_CHECK1                      1026
#define IDC_SCALETRACINGIMAGES          1027
#define IDC_MESSAGE                     1028
#define IDC_DONTSHOWAGAIN               1029
#define IDC_OPACITYPERCENT              1030
#define IDC_SLIDER                      1031
#define IDC_TAB2                        1032
#define IDC_EDITROOMNUMBER              1033
#define IDC_RADIOSAMEASROOM             1034
#define IDC_RADIOOTHER                  1035
#define IDC_EDITPICNUMBER               1036
#define IDC_LISTUSES                    1037
#define IDC_EDITNAME                    1042
#define IDC_CHECKSCRIPT                 1043
#define IDC_OBJECTTYPE                  1044
#define IDC_EDITAC                      1045
#define IDC_WORD                        1046
#define IDC_SCRIPTNAME                  1047
#define IDC_CHECKAUTOSUGGEST            1048
#define IDC_CHECKBRACESYNTAX            1049
#define IDC_EDIT_CELWIDTH               1050
#define IDC_EDIT_CELHEIGHT              1051
#define IDC_EDIT_CELX                   1052
#define IDC_EDIT_CELY                   1053
#define IDC_COMBO_MIRROR                1054
#define IDC_BUTTON_ADDCELBEFORE         1055
#define IDC_SPIN_CHOOSELOOP             1056
#define IDC_EDIT_CHOOSELOOP             1057
#define IDC_STATIC_MIRROROF             1058
#define IDC_BUTTON_ADDLOOPBEFORE        1059
#define IDC_STATIC_PALETTE              1060
#define IDC_STATIC_CHOSENCOLORS         1061
#define IDC_COMBO_PENWIDTH              1062
#define IDC_ANIMATE                     1063
#define IDC_COMBO_PALETTE               1063
#define IDC_EDIT_FINDWHAT               1064
#define IDC_WAVEFORM                    1064
#define IDC_LEVELMETER                  1064
#define IDC_CHECK_MATCHCASE             1065
#define IDC_CHECK_MATCHWHOLEWORD        1066
#define IDC_WAVEFORM2                   1066
#define IDC_RADIO_ALLFILES              1067
#define IDC_RADIO_OPENFILES             1068
#define IDC_CHECKAUTOLOADGAME           1069
#define IDC_PROGRESS                    1070
#define IDC_EDIT                        1071
#define IDC_CHECKDUPENEWCELS            1072
#define IDC_STATICSTATUS                1075
#define IDC_CHECKUSEBOXEGO              1076
#define IDC_STATIC_CELGROUP             1078
#define IDC_STATIC_LOOPGROUP            1079
#define IDC_CHECKSCI01                  1080
#define IDC_STATICPIC                   1081
#define IDC_CHECKHSL                    1082
#define IDC_STATICORIG                  1082
#define IDC_EDITNUMCOLORS               1083
#define IDC_STATICPICSIZE               1084
#define IDC_EDITSTATUS                  1085
#define IDC_CHECKSCALE                  1086
#define IDC_PROGRESSCONVERT             1087
#define IDC_CHECKINSERT                 1087
#define IDC_RADIO1                      1088
#define IDC_RADIO2                      1089
#define IDC_RADIO3                      1090
#define IDC_RADIO4                      1091
#define IDC_CHECKDITHER                 1091
#define IDC_SLIDERNUMCOLORS             1092
#define IDC_CHECKDITHER2                1092
#define IDC_CHECKDITHERALPHA            1092
#define IDC_RADIO5                      1093
#define IDC_RADIOHALFTONE               1094
#define IDC_RADIOSOLID                  1095
#define IDC_RADIOHALFTONESMOOTH         1096
#define IDC_SLIDERBRIGHTNESS            1098
#define IDC_SLIDERSATURATION            1099
#define IDC_SLIDERCONTRAST              1100
#define IDC_SLIDERTINTSTRENGTH          1100
#define IDC_STATICCONVERTTO             1101
#define IDC_CHECK_OPTION                1102
#define IDC_RADIOPICPALETTE             1103
#define IDC_CHECKIGNOREWHITE            1104
#define IDC_CHECK2                      1105
#define IDC_CHECKCOMPACTCODE            1106
#define IDC_EDIT_LINEHEIGHT             1107
#define IDC_EDIT_SAMPLE                 1111
#define IDC_EDITGAMENAME                1113
#define IDC_EDITEXECUTABLE              1115
#define IDC_CHECKAPPLYTOALL             1116
#define IDC_TREE_CLASS                  1117
#define IDC_CHECKISSCALEABLE            1117
#define IDC_CHECKISSCALABLE             1117
#define IDC_PROPERTIES                  1118
#define IDC_STATIC_CLASSNAME            1122
#define IDC_METHODS                     1124
#define IDC_INSTANCES                   1126
#define IDC_EDIT1                       1127
#define IDC_BROWSEINFO                  1128
#define IDC_EDITHEIGHT                  1128
#define IDC_SCRIPTNAV                   1129
#define IDC_CODECOMPLETION              1130
#define IDC_HOVERTIPS                   1131
#define IDC_LISTPROPS                   1132
#define IDC_LISTMETHODS                 1133
#define IDC_STATICVIEW                  1134
#define IDC_TREEOBJECTS                 1136
#define IDC_OBJECTNAME                  1137
#define IDC_PROPDESCRIPTION             1138
#define IDC_EDITERRORS                  1141
#define IDC_EDITPATH                    1142
#define IDC_SYNTAX_SCI                  1144
#define IDC_SYNTAX_CPP                  1145
#define IDC_RADIOCPP                    1146
#define IDC_RADIOSCISTUDIO              1147
#define IDC_STATICSCRIPTLANG            1148
#define IDC_STATICGENERAL               1149
#define IDC_STATICGAMENAME              1150
#define IDC_STATICEXE                   1151
#define IDC_STATICGROUP1                1152
#define IDC_STATICPROFILE               1152
#define IDC_STATICGROUP2                1153
#define IDC_STATICGROUP3                1154
#define IDC_STATICGROUP4                1155
#define IDC_STATIC1                     1156
#define IDC_STATIC2                     1157
#define IDC_STATIC3                     1158
#define IDC_STATIC4                     1159
#define IDC_STATIC5                     1160
#define IDC_STATIC6                     1161
#define IDC_GROUPSEARCH                 1162
#define IDC_STATIC7                     1162
#define IDC_GROUP1                      1163
#define IDC_STATIC10                    1163
#define IDC_LISTCOMMANDS                1164
#define IDC_STATIC11                    1164
#define IDC_LIST1                       1165
#define IDC_LISTSCRIPTS                 1165
#define IDC_LISTBOX_NOTES               1165
#define IDC_LISTNOUNS                   1165
#define IDC_LISTCOMMANDS2               1165
#define IDC_LISTPOLYGONS                1165
#define IDC_STATIC12                    1165
#define IDC_STATICVISUAL                1166
#define IDC_STATICCONTROL               1167
#define IDC_STATICPRIORITY              1168
#define IDC_GROUPVISUAL                 1169
#define IDC_STATICPALETTE               1170
#define IDC_GROUPPRIORITY               1171
#define IDC_EDITSCRIPT                  1171
#define IDC_GROUPCONTROL                1172
#define IDC_TREELOOPS                   1172
#define IDC_DECOMPILATIONRESULTS        1172
#define IDC_GOTOPIC                     1173
#define IDC_GOTOSCRIPT                  1174
#define IDC_GOTOPIC2                    1174
#define IDC_GOTOMESSAGE                 1174
#define IDC_NORTH                       1175
#define IDC_EAST                        1176
#define IDC_SOUTH                       1177
#define IDC_WEST                        1178
#define IDC_BUTTONPIC                   1179
#define IDC_BUTTONVIEWS                 1179
#define IDC_BUTTONSAMPLES               1180
#define IDC_BUTTON_DELETELOOP           1181
#define IDC_BUTTON_DELETECEL            1182
#define IDC_STATICUSES                  1183
#define IDC_PICGROUP                    1184
#define IDC_STATICROOMNUM               1185
#define IDC_STATICSCRIPTNAME            1186
#define IDC_STATICSCRIPTNUMBER          1187
#define IDC_COMPILEERRORSOUND           1188
#define IDC_COMBO_DEVICE                1191
#define IDC_EDIT_CHANNELS               1192
#define IDC_STATIC_DEVICE               1193
#define IDC_STATIC_SYNTH                1193
#define IDC_COMBO1                      1194
#define IDC_COMBO_MIDIDEVICE            1194
#define IDC_COMBODEVICE                 1194
#define IDC_STATIC_DEVICES              1195
#define IDC_COMBO2                      1195
#define IDC_BUTTON_STOP2                1196
#define IDC_COMBO3                      1196
#define IDC_BUTTON_PLAY                 1197
#define IDC_COMBOCONDITION              1197
#define IDC_COMBO4                      1197
#define IDC_CHECK_ALLCHANNELS           1198
#define IDC_COMBOVERB                   1198
#define IDC_COMBO6                      1198
#define IDC_LIST_CUES                   1199
#define IDC_BUTTON_PLAY2                1199
#define IDC_COMBO5                      1199
#define IDC_EDIT_VALUE                  1200
#define IDC_COMBOTALKER                 1200
#define IDC_BUTTON_ADDCUE               1201
#define IDC_BUTTON_DELETECUE            1202
#define IDC_EDIT_TIME                   1203
#define IDC_CHECK_CUMULATIVE            1204
#define IDC_CHECK_AUTOPREV              1205
#define IDC_STATICHEADER                1206
#define IDC_EDITEXECUTABLEPARAMETERS    1207
#define IDC_STATICEXEPARAM              1208
#define IDC_STATICSCRIPTNUM             1209
#define IDC_STATICQUESTION              1210
#define IDC_CHECKDELETE                 1211
#define IDC_CHECK_ENABLELOOPPOINT       1212
#define IDC_BUTTON_RECORD               1212
#define IDC_RADIOSCI0                   1212
#define IDC_BUTTON_STOP                 1213
#define IDC_RADIOSCI1                   1213
#define IDC_RADIOSCI2                   1214
#define IDC_RADIOSCI3                   1215
#define IDC_RADIOSCI4                   1216
#define IDC_RADIOSCI5                   1217
#define IDC_CHECK3                      1218
#define IDC_RADIOSCI7                   1218
#define IDC_CHECK4                      1219
#define IDC_CHECK5                      1220
#define IDC_RADIOSCI6                   1221
#define IDC_RADIOSCI8                   1222
#define IDC_RADIOSCI9                   1223
#define IDC_CHECKGLOBALPALETTE          1223
#define IDC_CHECK6                      1224
#define IDC_CHECKV                      1224
#define IDC_CHECK7                      1225
#define IDC_CHECKP                      1225
#define IDC_CHECK8                      1226
#define IDC_CHECKC                      1226
#define IDC_STATICZOOM                  1227
#define IDC_CHECK9                      1227
#define IDC_CHECK_FOLLOWVIEW            1228
#define IDC_RADIOSCI0_1                 1228
#define IDC_STATICFINAL                 1229
#define IDC_CHECKV2                     1230
#define IDC_EXTRACT                     1230
#define IDC_CHECKP2                     1231
#define IDC_CHECKC2                     1232
#define IDC_CHECK_FOLLOWVIEW2           1233
#define IDC_EDIT2                       1233
#define IDC_EDITTRANSPARENTCOLOR        1233
#define IDC_EDITRANGE                   1233
#define IDC_EDITSEQ                     1233
#define IDC_STATICTRANSLABEL            1234
#define IDC_CHECKDONTUSEINPALETTE       1235
#define IDC_BUTTONREVERT                1236
#define IDC_EDITALPHATHRESHOLD          1236
#define IDC_BUTTONEDITCOLOR             1237
#define IDC_STATICTRANSLABEL2           1237
#define IDC_STATICALPHALABEL            1237
#define IDC_BUTTON_SAVE                 1238
#define IDC_BUTTON_LOAD                 1239
#define IDC_TREESCO                     1239
#define IDC_DECOMPILE                   1240
#define IDC_BUTTONRANGEGRADIENT         1240
#define IDC_CLEARSCO                    1241
#define IDC_BUTTONADJUSTMENTS           1241
#define IDC_ASSIGNFILENAMES             1242
#define IDC_BUTTON_SAVERANGE            1242
#define IDC_DECOMPILECANCEL             1243
#define IDC_BUTTON_SAVEPALETTE          1243
#define IDC_DECOMPILESTATUS             1244
#define IDC_CHECKINSTRUCTIONCONSUMPTION 1245
#define IDC_CHECKCONTROLFLOW            1246
#define IDC_PROGRESS1                   1247
#define IDC_EDITDEBUGMATCH              1248
#define IDC_INSTRUCTIONS                1250
#define IDC_CHECKASM                    1251
#define IDC_LISTCONDITIONS              1252
#define IDC_BUTTONADDNOUN               1255
#define IDC_BUTTONADDCONDITION          1256
#define IDC_LISTVERBS                   1257
#define IDC_BUTTONDELETENOUN            1257
#define IDC_BUTTONADDVERB               1258
#define IDC_BUTTONDELETECONDITION       1258
#define IDC_BUTTONADDTALKER             1259
#define IDC_LISTTALKERS                 1260
#define IDC_EDITMESSAGE                 1261
#define IDC_BUTTONDELETEVERB            1261
#define IDC_COMBONOUN                   1262
#define IDC_BUTTONDELETETALKER          1262
#define IDC_SPINSEQ                     1263
#define IDC_STATIC8                     1264
#define IDC_STATIC9                     1265
#define IDC_BUTTONADDSEQ                1266
#define IDC_BUTTONCLONE                 1267
#define IDC_BUTTONCOMMIT                1268
#define IDC_BUTTONADDNEW                1269
#define IDC_CHECKMESSAGE                1269
#define IDC_BUTTONEDGES                 1270
#define IDC_CHECKPOLYS                  1270
#define IDC_BUTTONCENTER                1271
#define IDC_RADIOLINEAR                 1272
#define IDC_RADIOCENTER                 1273
#define IDC_COMBOTEMPLATE               1274
#define IDC_BUTTON_LOADAT               1275
#define IDC_CHECK10                     1276
#define IDC_CHECK11                     1277
#define IDC_EDITNUMCHARS                1278
#define IDC_CHECK12                     1278
#define IDC_BUTTONCYCLELEFT             1279
#define IDC_CHECKPREVIEWCYCLING         1280
#define IDC_BUTTONCYCLERIGHT            1281
#define IDC_STATIC_DURATION             1281
#define IDC_CHECK_ASPECTRATIO           1282
#define IDC_RADIOCOMMANDS               1283
#define IDC_RADIOPOLYGONS               1284
#define IDC_COMBOPOLYTYPE               1285
#define IDC_STATICPOLYTYPE              1286
#define IDC_CHECKSHOWPOLYS              1287
#define IDC_STATICRESNUM                1288
#define IDC_EDIT_POLYPOINTS             1289
#define IDC_STATICVERSION               1290
#define IDI_UPLOAD                      1291
#define IDC_STATICNAME                  1292
#define IDC_TABWHICHLIST                1293
#define IDC_EDIT_SAMPLEBIT              1294
#define IDC_EDIT_DESCRIPTION            1295
#define IDC_COMBOFROM                   1295
#define IDC_COMBOTO                     1296
#define IDC_STATICHUE                   1297
#define IDC_SLIDERHUE                   1298
#define IDC_EDITHUE                     1299
#define IDC_BUTTONCOLOR                 1300
#define IDC_STATICSATURATION            1301
#define IDC_EDITWIDTH                   1301
#define IDC_EDITSATURATION              1302
#define IDC_BUTTONREFRESH               1302
#define IDC_CHECKOVERLAY                1303
#define IDC_STATICBRIGHTNESS            1304
#define IDC_STATICGROUP                 1304
#define IDC_EDITBRIGHTNESS              1305
#define IDC_RADIOCEL                    1305
#define IDC_RADIOLOOP                   1306
#define IDC_STATICTITLE                 1306
#define IDC_STATICTINTSTRENGTH          1307
#define IDC_RADIOVIEW                   1307
#define IDC_SLIDERCYCLESPEED            1307
#define IDC_EDITTINTSTRENGTH            1308
#define IDC_BUTTONPENSTYLE              1308
#define IDC_EDITRANGES                  1309
#define IDC_STATICARROW                 1310
#define IDC_COMBOMATCH                  1311
#define IDC_COMBODITHERALPHA            1312
#define IDC_STATICDITHERALPHA           1313
#define IDC_COMBO_WAVEFORMAT            1314
#define IDC_BUTTONLIPSYNC               1315
#define IDC_EDIT_WORDS                  1316
#define IDC_BUTTONLIPSYNC_DIALOG        1316
#define IDC_STATIC_WORDS                1317
#define IDC_LIST_SYNCRESOURCE           1319
#define IDC_STATIC_TALKER               1320
#define IDC_EDIT_PHONEMEMAP             1322
#define IDC_STATIC_PHONEME              1323
#define IDC_BUTTON_RESETMAPPING         1324
#define IDC_EDIT_PHONEMEMAPSTATUS       1325
#define IDC_CHECK_HALFSPEED             1326
#define IDC_STATIC_SYNC36               1327
#define IDC_BUTTON_COMMITMAPPING        1328
#define IDC_BUTTON_RELOADMAPPING        1328
#define IDC_BUTTON_SETVIEW              1329
#define IDC_CHECK_USESAMPLE             1330
#define IDC_EDITVIEW                    1331
#define IDC_BUTTON_RESETMAPPING2        1331
#define IDC_BUTTON_OPENMAPPING          1331
#define IDC_EDITLOOP                    1332
#define IDC_GROUP_VIEWLOOP              1333
#define IDC_GROUP_MESSAGE               1334
#define IDC_GROUP_TALKER                1335
#define IDC_BUTTON_DELETE_SYNC          1336
#define IDC_BUTTON_RAW                  1337
#define IDC_STATIC_BASE36NAME           1337
#define IDC_STATIC_REC                  1338
#define IDC_BUTTON_EXPORTSYNC           1338
#define IDC_CHECK_TEXTLESS              1339
#define IDC_BUTTON_IMPORTSYNC           1339
#define IDC_CHECK_MONITOR               1340
#define IDC_EDIT_TRIMLEFT               1341
#define IDC_EDIT_TRIMRIGHT              1342
#define IDC_GROUP2                      1343
#define IDC_CHECK_USETEXT               1344
#define IDC_BUTTON_REPACKAGE            1346
#define IDC_BUTTON_CLEARAUDIOCACHE      1347
#define IDC_CHECK_AUTOGAIN              1348
#define IDC_CHECK_DETECTSTARTEND        1349
#define IDC_EDIT_ATTACK                 1350
#define IDC_EDIT_RELEASE                1351
#define IDC_EDIT_HOLD                   1352
#define IDC_STATIC_ATTACK               1353
#define IDC_STATIC_HOLD                 1354
#define IDC_STATIC_RELEASE              1355
#define IDC_EDIT_OPENTHR                1356
#define IDC_STATIC_OPENTHR              1357
#define IDC_EDIT_CLOSETHR               1358
#define IDC_STATIC_CLOSETHR             1359
#define IDC_STATIC_TRIM                 1360
#define IDC_STATIC_PRESET               1361
#define IDC_EDITPHONEMEMAP              1362
#define IDC_CHECK_AUDIODITHER           1362
#define IDC_COMBO_BIT                   1363
#define IDC_RADIO_NEGATIVE              1364
#define IDC_RADIO_FINAL                 1365
#define IDC_COMBO_PRESET2               1366
#define IDC_PHONEME                     1366
#define IDC_EDIT_DESCRIPTION2           1367
#define IDC_BUTTON_PROCESS              1368
#define IDC_EDITAUDIO                   1369
#define IDC_SPIN_LIPSYNC                1370
#define IDC_CHECK_COMPRESSION           1371
#define IDC_STATIC_CLIPPED              1372
#define IDC_BUTTONDELETEAUDIO           1373
#define IDC_STATIC_IMAGE                1374
#define IDC_GROUP_AUDIO                 1375
#define IDC_COMBOPROFILE                1376
#define ID_PENTOOL                      32771
#define ID_ZOOM                         32773
#define ID_HISTORY                      32775
#define ID_FILL                         32776
#define ID_LINE                         32777
#define ID_TRACEBITMAP                  32778
#define ID_SHOWTRACEIMAGE               32784
#define ID_SETVISUAL                    32788
#define ID_SETPRIORITY                  32789
#define ID_DRAWOFF                      32790
#define ID_SHOWVISUALSCREEN             32791
#define ID_SHOWPALETTE0                 32792
#define ID_SHOWPRIORITYSCREEN           32793
#define ID_SHOWCONTROLSCREEN            32794
#define ID_SHOWSCREENLABEL              32795
#define ID_SHOWVISUALSCREEN2            32796
#define ID_SETCONTROL                   32797
#define ID_SHOWPALETTE2                 32798
#define ID_TOGGLEPRIORITYLINES          32799
#define ID_SHOWPALETTE3                 32800
#define ID_SHOWVISUALSCREEN5            32801
#define ID_SHOWPALETTE1                 32802
#define ID_TOGGLEEGO                    32803
#define ID_FILE_NEWPIC                  32804
#define ID_VIEWTHUMBNAILS               32805
#define ID_VIEWDETAILS                  32806
#define ID_DELETECOMMAND                32807
#define ID_CROPCOMMANDS                 32808
#define ID_DEFINEPALETTES               32809
#define ID_PREFERENCES                  32821
#define ID_FILE_OPENRESOURCE            32829
#define ID_FILE_EXPORTASRESOURCE        32830
#define ID_COPYCOMMANDS                 32832
#define ID_COMPILE                      32838
#define ID_RUNGAME                      32839
#define ID_NEWROOM                      32840
#define ID_INSERTOBJECT                 32842
#define ID_NEWSCRIPT                    32843
#define ID_COMPILEALL                   32844
#define ID_EDIT_DELETE                  32847
#define ID_MAIN_ADDAS                   32854
#define ID_ADDAS_NOUN                   32855
#define ID_ADDAS_IMPERATIVEVERB         32856
#define ID_Menu                         32857
#define ID_ADDAS_SYNONYMOF              32858
#define ID_ADDAS_PREPOSITION            32859
#define ID_ADDAS_ARTICLE                32860
#define ID_ADDAS_QUALIFYINGADJECTIVE    32861
#define ID_ADDAS_RELATIVEPRONOUN        32862
#define ID_ADDAS_INDICATIVEVERB         32863
#define ID_ADDAS_ADVERB                 32864
#define ID_GOTOSCRIPT                   32865
#define ID_OPEN_EXPLORERWINDOW          32866
#define ID_TOOLS_REBUILDRESOURCES       32869
#define ID_VIEW                         32871
#define ID_EDIT_ERASETHISCMD            32872
#define ID_VOCAB_NUMBER                 32882
#define ID_VOCAB_PREPOSITION            32883
#define ID_VOCAB_ARTICLE                32884
#define ID_VOCAB_QUALIFYINGADJECTIVE    32885
#define ID_VOCAB_RELATIVEPRONOUN        32886
#define ID_VOCAB_NOUN                   32887
#define ID_VOCAB_INDICATIVEVERB         32888
#define ID_VOCAB_ADVERB                 32889
#define ID_VOCAB_IMPERATIVEVERB         32890
#define ID_VOCAB_NEWWORD                32893
#define ID_EDIT_RENAME                  32894
#define ID_DRAWRECT                     32895
#define ID_DRAWRECTSOLID                32896
#define ID_DRAWOVAL                     32897
#define ID_BUTTON32898                  32898
#define ID_DRAWOVALSOLID                32898
#define ID_SELECT                       32900
#define ID_SETPLACEMENT                 32903
#define ID_FLIPHORZ                     32905
#define ID_FLIPVERT                     32906
#define ID_GREYSCALE                    32907
#define ID_INVERT                       32908
#define ID_FILE_NEWVIEW                 32910
#define ID_MAKEFONT                     32911
#define ID_REPLACE                      32913
#define ID_ANIMATE                      32923
#define ID_DRAWROUNDEDRECTSOLID         32924
#define ID_DRAWROUNDEDRECT              32925
#define ID_EDIT_FINDINFILES             32928
#define ID_FILE_CLOSEGAME               32937
#define ID_EDIT_PASTETRANSPARENT        32942
#define ID_EDIT_IMPORTPICBACKGROUND     32945
#define ID_EDIT_SELECTALL               32948
#define ID_BUTTON32954                  32954
#define ID_DITHER                       32954
#define ID_FILE_ADDRESOURCE             32963
#define ID_LIGHTUPCOORDS                32964
#define ID_VIEW_ZOOMIN                  32969
#define ID_VIEW_ZOOMOUT                 32970
#define ID_Menu32978                    32978
#define ID_HELP_ONLINESCIDOCUMENTATION  32979
#define ID_HELP_ONLINETUTORIALS         32980
#define ID_MOVEDOWN                     32985
#define ID_MOVEUP                       32986
#define ID_HELP_EMAIL                   32988
#define ID_HELP_GETLATESTUPDATES        32989
#define ID_GAME_PROPERTIES              32990
#define ID_VIEWBG_VIEW                  32995
#define ID_IMPORT_BITMAPSEQUENCE        33000
#define ID_IMPORT_IMAGESEQUENCE         33001
#define ID_FILE_NEWFONT                 33002
#define ID_FILE_NEWCURSOR               33003
#define ID_FILE_NEWTEXT                 33004
#define ID_FILE_SCRIPTEDITOR            33005
#define ID_HELP_SCICOMPANION            33011
#define ID_INTELLISENSE                 33012
#define ID_RECORD                       33014
#define ID_CLASSBROWSER                 33015
#define ID_ROOM_EXPLORER                33017
#define ID_EDIT_GOTO                    33018
#define ID_SCRIPT_GOTODEFINITION        33021
#define ID_DEFAULTPRIORITY              33024
#define ID_MAIN_PRI0                    33025
#define ID_MAIN_PRI1                    33026
#define ID_MAIN_PRI2                    33027
#define ID_MAIN_PRI3                    33028
#define ID_MAIN_PRI4                    33029
#define ID_MAIN_PRI5                    33030
#define ID_MAIN_PRI6                    33031
#define ID_MAIN_PRI7                    33032
#define ID_MAIN_PRI8                    33033
#define ID_MAIN_PRI9                    33034
#define ID_MAIN_PRI10                   33035
#define ID_MAIN_PRI11                   33036
#define ID_MAIN_PRI12                   33037
#define ID_MAIN_PRI13                   33038
#define ID_MAIN_PRI14                   33039
#define ID_MAIN_PRI15                   33040
#define ID_VISUALSCRIPT                 33041
#define ID_NEWCOMPILE                   33045
#define ID_SCRIPT_DISASSEMBLE           33047
#define ID_SCRIPT_VIEWOBJECTFILE        33048
#define ID_SCRIPT_VIEWSCRIPTRESOURCE    33049
#define ID_SCRIPT_VIEWSYNTAXTREE        33052
#define ID_FILE_NEWGAME                 33054
#define ID_CONVERTSCRIPT                33055
#define ID_CIRCLE                       33056
#define ID_SCREENS                      33057
#define ID_PALETTES                     33058
#define ID_ZOOMSLIDER                   33059
#define ID_SHOW_VIEWS                   33060
#define ID_SHOW_PICS                    33061
#define ID_SHOW_SCRIPTS                 33062
#define ID_SHOW_TEXTS                   33063
#define ID_SHOW_SOUNDS                  33064
#define ID_SHOW_MEMORY                  33065
#define ID_SHOW_VOCABS                  33066
#define ID_SHOW_FONTS                   33067
#define ID_SHOW_CURSORS                 33068
#define ID_SHOW_PATCHES                 33069
#define ID_WINDOW                       33070
#define ID_WINDOW_DUMMY                 33071
#define ID_ALPHASLIDER                  33072
#define ID_GOTOVIEW1                    33073
#define ID_GOTOVIEW2                    33074
#define ID_GOTOVIEW3                    33075
#define ID_GOTOVIEW4                    33076
#define ID_GOTOVIEW5                    33077
#define ID_GOTOVIEW6                    33078
#define ID_GOTOVIEW7                    33079
#define ID_GOTOVIEW8                    33080
#define ID_GOTOVIEW9                    33081
#define ID_GOTOVIEW10                   33082
#define ID_GOTOVIEW11                   33083
#define ID_GOTOVIEW12                   33084
#define ID_GOTOVIEW13                   33085
#define ID_GOTOVIEW14                   33086
#define ID_GOTOVIEW15                   33087
#define ID_GOTOVIEW16                   33088
#define ID_GOTOVIEW17                   33089
#define ID_GOTOVIEW18                   33090
#define ID_GOTOVIEW19                   33091
#define ID_GOTOVIEW20                   33092
#define ID_GOTOVIEW21                   33093
#define ID_GOTOVIEW22                   33094
#define ID_GOTOVIEW23                   33095
#define ID_GOTOVIEW24                   33096
#define ID_GOTOVIEW25                   33097
#define ID_GOTOVIEW26                   33098
#define ID_GOTOVIEW27                   33099
#define ID_GOTOVIEW28                   33100
#define ID_VIEWMENU                     33107
#define ID_PLACEHOLDER_VIEWS            33108
#define ID_BACK                         33109
#define ID_FORWARD                      33110
#define ID_BAR_GAME                     33111
#define ID_BAR_TOOLBOX                  33112
#define ID_BAR_OUTPUT                   33113
#define ID_CONTROL_OUTPUTPANE           33114
#define ID_BAR_TOOLPIC                  33115
#define ID_BAR_TOOLSCRIPT               33116
#define ID_BAR_TOOLEXPLORER             33117
#define ID_BAR_TOOLTEXT                 33118
#define ID_BAR_TOOLRASTER               33119
#define ID_BAR_TOOLVOCAB                33120
#define ID_BAR_VPC                      33121
#define ID_BAR_TOOLSOUND                33122
#define ID_BAR_PREVIEW                  33123
#define ID_FILE_EXPORTASBITMAP          33124
#define ID_SELFTEST                     33125
#define ID_HELP_FORUMS                  33127
#define ID_OBSERVECONTROLLINES          33131
#define ID_FILE_NEWSOUND                33137
#define ID_PLAY                         33138
#define ID_STOP                         33139
#define ID_IMPORT_MIDI                  33140
#define ID_TEMPOSLIDER                  33141
#define ID_PAUSE                        33142
#define ID__                            33145
#define ID_COMPILEDOCS                  33147
#define ID_SCRIPT_DECOMPILE             33154
#define ID_SHOW_PALETTES                33155
#define ID_GAME_VERSIONDETECTION        33156
#define ID_EYEDROPPER                   33157
#define ID_SETTRANSPARENCY              33158
#define ID_SHOW_MESSAGES                33159
#define ID_VIEWITEM_VIEWRAWDATA         33160
#define ID_GAME_ROOMEXPLORER            33161
#define ID_INDICATOR_LINECOUNT          33162
#define ID_INDICATOR_RASTERSIZE         33163
#define ID_INDICATOR_PIXELCOLOR         33164
#define ID_INDICATOR_RESCOUNT           33165
#define ID_INDICATOR_CONTROLCOLOR       33166
#define ID_INDICATOR_PRICOLOR           33167
#define ID_SHOW_HEAPS                   33168
#define ID_PIC_EXPORT8                  33169
#define ID_BAR_PICHELPER                33170
#define ID_TOOLS_EXTRACTALLRESOURCES    33171
#define ID_PIC_EDITPALETTE              33172
#define ID_EDITPALETTE                  33173
#define ID_UPLOAD                       33173
#define ID_MAIN_EDITPALETTE             33174
#define ID_UPLOADNAME                   33174
#define ID_VIEW_EDITPALETTE             33175
#define ID_MAIN_DELETEPOIN              33176
#define ID_PIC_DELETEPOINT              33177
#define ID_SHOW_AUDIO                   33178
#define ID_SCRIPT_MANAGEDECOMPILATION   33179
#define ID_TOOLS_REBUILDCLASSTABLE      33180
#define ID_BAR_MESSAGEEDIT              33181
#define ID_NEW_MESSAGE                  33182
#define ID_NEW_PALETTE                  33183
#define ID_BAR_TOOLMESSAGE              33184
#define ID_VIEW_REMOVEEMBEDDEDPALETTE   33185
#define ID_POLYPATH                     33188
#define ID_PIC_SPLITEDGE                33189
#define ID_DEBUGGAME                    33190
#define ID_DEBUGROOM                    33191
#define ID_STOPDEBUG                    33192
#define ID_GAME_DEBUGGAME               33193
#define ID_GAME_STOPDEBUGGING           33194
#define ID_SCRIPT_DEBUGROOM             33195
#define ID_Menu33196                    33196
#define ID_OBSERVEPOLYGONS              33197
#define ID_VIEW_REMAPPALETTE            33198
#define ID_MESSAGE_EXPORTTOTEXTFILE     33199
#define ID_MESSAGE_EXPORT               33200
#define ID_MESSAGE_IMPORTFROMTEXTFILE   33201
#define ID_MESSAGE_IMPORT               33202
#define ID_MESSAGE_ADDNEW               33203
#define ID_MESSAGE_ADDSEQUENCE          33204
#define ID_MESSAGE_ADDCLONE             33205
#define ID_PIC_CHANGEDIMENSIONS         33206
#define ID_PIC_REMOVESETVISUAL          33207
#define ID_VIEW_SHIFTCOLORS             33208
#define ID_VIEW_EXPORTASGIF             33209
#define ID_MAIN_INSERTOBJECT            33210
#define ID_INSERTOBJECTAT               33211
#define ID_INSERTOBJECTAT1              33212
#define ID_INSERTOBJECTAT2              33213
#define ID_INSERTOBJECTAT3              33214
#define ID_INSERTOBJECTAT4              33215
#define ID_INSERTOBJECTAT5              33216
#define ID_INSERTOBJECTAT6              33217
#define ID_INSERTOBJECTAT7              33218
#define ID_INSERTOBJECTAT8              33219
#define ID_INSERTOBJECTAT9              33220
#define ID_INSERTOBJECTAT10             33221
#define ID_INSERTOBJECTAT11             33222
#define ID_INSERTOBJECTAT12             33223
#define ID_INSERTOBJECTAT13             33224
#define ID_INSERTOBJECTAT14             33225
#define ID_INSERTOBJECTAT15             33226
#define ID_INSERTOBJECTAT16             33227
#define ID_INSERTOBJECTAT17             33228
#define ID_INSERTOBJECTAT18             33229
#define ID_INSERTMETHODAT               33230
#define ID_INSERTMETHODAT1              33231
#define ID_INSERTMETHODAT2              33232
#define ID_INSERTMETHODAT3              33233
#define ID_INSERTMETHODAT4              33234
#define ID_INSERTMETHODAT5              33235
#define ID_INSERTMETHODAT6              33236
#define ID_INSERTMETHODAT7              33237
#define ID_INSERTMETHODAT8              33238
#define ID_INSERTMETHODAT9              33239
#define ID_INSERTMETHODAT10             33240
#define ID_INSERTMETHODAT11             33241
#define ID_INSERTMETHODAT12             33242
#define ID_INSERTMETHODAT13             33243
#define ID_INSERTMETHODAT14             33244
#define ID_INSERTMETHODAT15             33245
#define ID_INSERTMETHODAT16             33246
#define ID_INSERTMETHODAT17             33247
#define ID_INSERTMETHODAT18             33248
#define ID_MAIN_INSERTMETHOD            33249
#define ID_MAIN_INSERTMETHOD33250       33250
#define ID_INSERTMETHOD_DELETEME        33251
#define ID_MAIN_INSERTMETHOD33252       33252
#define ID_INSERTMETHOD_DELETEME33253   33253
#define ID_VIEW_EXPORT                  33254
#define ID_EXPORT_LOOPASGIF             33255
#define ID_EXPORT_ASENCODEDBITMAP       33256
#define ID_EXPORT_VIEWASIMAGE           33257
#define ID_EXPORT_LOOPASIMAGE           33258
#define ID_EXPORT_CELASIMAGE            33259
#define ID_ROOTITEM_ANOTHERITEM         33260
#define ID_FAKEEGONUMBER                33261
#define ID_FAKEEGO0                     33262
#define ID_FAKEEGO1                     33263
#define ID_FAKEEGO2                     33264
#define ID_FAKEEGO3                     33265
#define ID_FAKEEGO4                     33266
#define ID_FAKEEGO5                     33267
#define ID_FAKEEGO6                     33268
#define ID_FAKEEGO7                     33269
#define ID_FAKEEGO8                     33270
#define ID_FAKEEGO9                     33271
#define ID_FAKEEGO10                    33272
#define ID_FAKEEGO11                    33273
#define ID_FAKEEGO12                    33274
#define ID_TOOLS_AUDIOPREFERENCES       33275
#define ID_TOOLS_REPACKAGEAUDIO         33276
#define ID_INDICATOR_PRI                59138
#define ID_INDICATOR_COORDS             59142

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        399
#define _APS_NEXT_COMMAND_VALUE         33277
#define _APS_NEXT_CONTROL_VALUE         1377
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
