#if (!defined __PROF_UIS_RES_CC_SC_H)
#define __PROF_UIS_RES_CC_SC_H

#define IDB_EXT_BITMAP_TREE_BOX_COLLAPSED_XP                   29700
#define IDB_EXT_BITMAP_TREE_BOX_COLLAPSED_HOVER_XP             29701
#define IDB_EXT_BITMAP_TREE_BOX_EXPANDED_XP                    29702
#define IDB_EXT_BITMAP_TREE_BOX_EXPANDED_HOVER_XP              29703

#define IDB_EXT_BITMAP_TREE_BOX_COLLAPSED_VISTA                29704
#define IDB_EXT_BITMAP_TREE_BOX_COLLAPSED_HOVER_VISTA          29705
#define IDB_EXT_BITMAP_TREE_BOX_EXPANDED_VISTA                 29706
#define IDB_EXT_BITMAP_TREE_BOX_EXPANDED_HOVER_VISTA           29707

#endif

